#define _CRT_SECURE_NO_WARNINGS
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#include "head.h"
#include "function.h"
#include "cmd.h"

status fgetName(matrix* m, FILE* s)
{
	char buffer[MAX_BUFFER];
	if(fgetLine(buffer, sizeof(buffer), s)==NULL) return INVALID_INPUT;
	char* str = NotBlank(buffer);
	removeTailBlk(str);
	int len = strlen(str);
	if (len == 0) return INVALID_INPUT;
	if (len >= MAX_NAME - 1)
	{
		return NAME_TOO_LONG;
	}
	
	strcpy(m->name, str);
	return SUCCESS;
}

status fgetSize(int* x, FILE* s)
{
	char buffer[MAX_BUFFER];
	fgetLine(buffer, sizeof(buffer), s);
	if (parseInt(buffer, x) == 0) return INVALID_INPUT;
	if (*x <= 0) return INVALID_INPUT;
	if (*x > MAX_ROW) return MAT_SIZE_EXD;
	return SUCCESS;
}

status fgetMatrix(matrix* m,FILE* s)
{
	m->arr = (frac**)malloc2dArr(m->r, m->c, sizeof(m->arr[0][0]));
	if (m->arr == NULL) return MEMORY_FAIL;
	char buffer[MAX_BUFFER];
	int i;
	for (i = 0; i < m->r; i++)
	{
		fgetLine(buffer, sizeof(buffer), s);
		int j;
		char* str = buffer;
		for (j = 0; j < m->c; j++)
		{
			int len = parseFrac(str, &(m->arr[i][j]));
			if (len == 0)
			{
				delMat(m);
				return LACK_INDEX;
			}
			simFrac(&(m->arr[i][j]));
			str += len;
		}
	}
	return SUCCESS;
}

status open(context* idx)
{
	//检查是否还有多余空间
	if (idx->matCnt >= MAX_MATRIX - 1) return MEMORY_FAIL;

	matrix tmp = { "",0,0,NULL };

	//输入文件位置
	puts("file path>>(path of your file,such as \"D:\\matrix\\mat.txt\")");
	char buffer[MAX_BUFFER];
	getLine(buffer,sizeof(buffer));
	char* str = NotBlank(buffer);
	removeTailBlk(buffer);
	if (str[0] == '\0')
	{
		return INVALID_INPUT;
	}

	//打开文件
	FILE* s = fopen(str, "r");
	if (s == NULL) return FILE_PATH_INVALID;

	//开始读取
	status st;

	//读入名字
	st = fgetName(&tmp, s);
	if (st != SUCCESS) return st;
	if (searchMat(idx->matList, idx->matCnt, tmp.name) != -1)
	{
		fclose(s);
		return REPEAT_NAME;
	}

	//读入行、列
	st = fgetSize(&tmp.r, s);
	if (st != SUCCESS)
	{
		fclose(s);
		return st;
	}
	st = fgetSize(&tmp.c, s);
	if (st != SUCCESS)
	{
		fclose(s);
		return st;
	}

	//读入矩阵
	st = fgetMatrix(&tmp, s);
	if (st != SUCCESS)
	{
		fclose(s);
		return st;
	}

	//载入列表
	memcpy( &idx->matList[idx->matCnt++], &tmp, sizeof(tmp));

	//关闭文件
	fclose(s);
	printf("The matrix has been read in as \"%s\"\n", idx->matList[idx->matCnt - 1].name);
	return SUCCESS;
}

command cmd_open = { "open",open,"open a local matrix file and add it to the list.\nNOTE:The format is the same as your input in the \"new\" command.\n\
You may also check out that format in the file generated by the \"save\" command." };